import {makeId,defaults,validateState,start,elapsed,togglePause,stop,advance,nextBreak,range,inRange,reward,dayStart} from './engine.mjs';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=validateState(window.FOCUS_INITIAL||defaults()),page='focus',period='M',anchor=Date.now(),calendarMode='W',calendarAnchor=Date.now(),readOnly=false;
const win=$('#window'),modal=$('#modal'),theme={focus:'dark',tags:'dark',pomodoro:'dark',trend:'light',calendar:'light'};
const send=(type,body={})=>parent.postMessage({type,...body},'*');
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('visible'),4000)}
function changed(){if(readOnly)return;send('focus-save',{state:structuredClone(state)});render();syncBodies()}
function go(name){if(!theme[name])return;page=name;$$('.page').forEach(p=>p.classList.toggle('active',p.dataset.page===name));win.classList.toggle('theme-light',theme[name]==='light');win.classList.toggle('theme-dark',theme[name]!=='light');$('#newTagBtn').classList.toggle('hidden',name!=='tags');$('#backBtn').classList.toggle('hidden',name==='focus');$('#menuPopover').classList.add('hidden');render();resize()}
function tag(id){return state.tags.find(t=>t.id===id)||state.tags[0]}
function fmt(seconds){seconds=Math.max(0,Math.floor(seconds));return `${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`}
function human(seconds){const m=Math.floor(seconds/60);return m>=60?`${Math.floor(m/60)} 小时 ${m%60} 分钟`:`${m} 分钟`}
function buttons(items){return '<div class="dialog-actions">'+items.map(([id,text,cls=''])=>`<button id="${id}" class="${cls}">${text}</button>`).join('')+'</div>'}
function show(title,html,items=[['closeDialog','关闭']]){$('#modalContent').innerHTML=`<h2>${esc(title)}</h2>${html}${buttons(items)}`;if(!modal.open)modal.showModal();$('#closeDialog')?.addEventListener('click',()=>modal.close())}
function startFocus(minutes=state.settings.minutes){if(readOnly||state.active)return;start(state,{minutes});changed();send('focus-awake',{active:true});go('focus')}
function complete(natural=false,outcome='finished'){
 if(!state.active||readOnly)return;
 const row=stop(state,{natural,outcome});changed();send('focus-awake',{active:false});if(!row.rest&&outcome==='finished')finished(row);
}
function finished(row){
 if(state.settings.sound)beep();
 send('focus-notify',{title:'专注完成',body:human(row.seconds)});
 show('专注完成',`<img class="finish-tomato" src="assets/tomato.png" alt="番茄"><p>${esc(tag(row.tagId).name)} · ${human(row.seconds)}</p>`,[['restNow',`休息 ${nextBreak(state)} 分钟`,'primary'],['againNow','继续专注'],['closeDialog','回到首页']]);
 $('#restNow').onclick=()=>{modal.close();start(state,{rest:true,minutes:nextBreak(state)});changed()};$('#againNow').onclick=()=>{modal.close();startFocus()};
}
$('#startFocus').onclick=()=>{if(state.pendingRest){show('准备好继续了吗？','',[['restNow',`休息 ${nextBreak(state)} 分钟`,'primary'],['againNow','开始下一轮'],['closeDialog','取消']]);$('#restNow').onclick=()=>{modal.close();start(state,{rest:true,minutes:nextBreak(state)});changed()};$('#againNow').onclick=()=>{modal.close();startFocus()}}else startFocus()};
$('#pauseBtn').onclick=()=>{if(togglePause(state)){changed()}};
$('#finishBtn').onclick=()=>{
 if(!state.active)return;
 if(state.active.mode==='rest'){complete();return}
 show('结束本次专注？','<p>可以保留这段专注，或将它记为放弃。</p>',[['finishSession','保留为已完成','primary'],['abandonSession','放弃','danger'],['closeDialog','继续专注']]);
 $('#finishSession').onclick=()=>{modal.close();complete(false,'finished')};$('#abandonSession').onclick=()=>{modal.close();complete(false,'abandoned')};
};
$('#timerValue').onclick=()=>{if(!state.active){$('#durationPopover').classList.remove('hidden');$('#customMinutes').value=state.settings.minutes||''}};
let durationChoice=null;$$('[data-min]').forEach(b=>b.onclick=()=>{durationChoice=+b.dataset.min;$('#customMinutes').value=durationChoice||'';$$('[data-min]').forEach(x=>x.classList.toggle('active',x===b))});
$('#customMinutes').oninput=()=>durationChoice=null;
$('#durationDone').onclick=()=>{const m=durationChoice??Number($('#customMinutes').value);if(!Number.isInteger(m)||m<0||m>180)return toast('请输入 1—180 分钟，或选 ∞ 正计时');state.settings.minutes=m;durationChoice=null;$('#durationPopover').classList.add('hidden');changed()};
$('#focusTask').onclick=()=>state.active?toast('本轮结束后可以切换标签'):go('tags');
$('#menuBtn').onclick=e=>{e.stopPropagation();$('#menuPopover').classList.toggle('hidden')};
$('#backBtn').onclick=()=>go('focus');$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
document.addEventListener('click',e=>{if(!$('#menuPopover').contains(e.target)&&!$('#menuBtn').contains(e.target))$('#menuPopover').classList.add('hidden')});
$('#exitBtn').onclick=()=>send('focus-exit');
$('#newTagBtn').onclick=()=>editTag();
function editTag(existing){
 show(existing?'编辑标签':'新标签',`<form id="tagForm"><label>标签名称<input id="tagName" maxlength="80" required value="${esc(existing?.name||'')}"></label><label>颜色<input id="tagColor" type="color" value="${existing?.color||'#ef8b24'}"></label><label>默认分钟（0 为正计时）<input id="tagMinutes" type="number" min="0" max="180" value="${existing?.minutes??25}" required></label></form>`,[['saveTag','保存','primary'],...(existing?[["archiveTag",existing.archived?'取消归档':'归档'],['moveTag','向前移动']]:[]),['closeDialog','取消']]);
 $('#saveTag').onclick=()=>{const name=$('#tagName').value.trim(),minutes=Number($('#tagMinutes').value);if(!name||!Number.isInteger(minutes)||minutes<0||minutes>180)return toast('请检查名称和时长');if(existing)Object.assign(existing,{name,color:$('#tagColor').value,minutes});else state.tags.push({id:makeId(),name,color:$('#tagColor').value,minutes,archived:false});modal.close();changed()};
 $('#archiveTag')?.addEventListener('click',()=>{if(!existing.archived&&state.tags.filter(t=>!t.archived).length<2)return toast('至少保留一个可用标签');existing.archived=!existing.archived;if(existing.archived&&state.selectedTag===existing.id)state.selectedTag=state.tags.find(t=>!t.archived).id;modal.close();changed()});
 $('#moveTag')?.addEventListener('click',()=>{const i=state.tags.indexOf(existing);if(i>0)[state.tags[i-1],state.tags[i]]=[state.tags[i],state.tags[i-1]];modal.close();changed()});
}
function renderTags(){
 $('#tagsGrid').innerHTML=state.tags.map(t=>`<div class="tag-row"><button class="tag-pill ${t.id===state.selectedTag?'active':''} ${t.archived?'archived':''}" style="--tag-color:${t.color}" data-tag="${esc(t.id)}"><i class="dot" style="background:${t.color}"></i><span class="tag-copy"><b>${esc(t.name)}</b><small>${t.archived?'已归档':t.minutes?fmt(t.minutes*60):'正计时'}</small></span></button><button class="tag-edit" data-edit-tag="${esc(t.id)}" aria-label="编辑 ${esc(t.name)}">···</button></div>`).join('');
 $$('[data-tag]').forEach(b=>b.onclick=()=>{const t=tag(b.dataset.tag);if(t.archived)return editTag(t);if(state.active)return toast('请先结束本轮专注');state.selectedTag=t.id;state.settings.minutes=t.minutes;changed();go('focus')});
 $$('[data-edit-tag]').forEach(b=>b.onclick=()=>editTag(tag(b.dataset.editTag)));
 const fruits=visibleTomatoes().slice(-160);$('#tagsTomatoField').innerHTML=fruits.map((r,i)=>`<img src="assets/tomato-small.png" style="left:${(i*31)%97}%;bottom:${(i*47)%260}px" alt="">`).join('');
}
function renderTimer(){const a=state.active;win.classList.toggle('is-running',!!a);$('#timerValue').textContent=a?(a.kind==='up'?fmt(elapsed(a)):fmt(Math.ceil(Math.max(0,a.targetSeconds-elapsed(a))))):state.settings.minutes?fmt(state.settings.minutes*60):'00:00';$('#focusTask').innerHTML=`${a?.mode==='rest'?'休息':esc(tag(a?.tagId||state.selectedTag).name)} <span>›</span>`;$('#startFocus').classList.toggle('hidden',!!a);$('#startFocus').textContent=state.pendingRest?'下一步':'开始专注';$('#focusControls').classList.toggle('hidden',!a);$('#pauseBtn').classList.toggle('hidden',!a||a.kind!=='up'||a.mode!=='focus');$('#pauseIcon').textContent=a?.paused?'▶':'Ⅱ';$('#pauseLabel').textContent=a?.paused?'继续':'暂停';$('#focusMeta').textContent=a?.mode==='rest'?'休息中':a?.paused?'已暂停':a?'专注中':`${visibleTomatoes().filter(reward).length} 个番茄`;}
function visibleTomatoes(){let p='W',a=Date.now();if(state.settings.window==='lastweek')a-=7*864e5;if(state.settings.window==='month'||state.settings.window==='quarter')p='M';let r=range(p,a);if(state.settings.window==='quarter'){let d=new Date(r.start);d.setMonth(d.getMonth()-2);r.start=d.getTime()}return inRange(state.sessions,r).filter(x=>reward(x)||(state.settings.showFailed&&!x.manual&&x.outcome==='abandoned'))}
function currentRows(){return inRange(state.sessions,range(period,anchor))}
function metrics(rows){const done=rows.filter(r=>r.outcome==='finished'),seconds=done.reduce((s,r)=>s+r.seconds,0),count=done.filter(reward).length;const r=range(period,anchor),days=Math.max(1,Math.round((Math.min(r.end,dayStart(Date.now())+864e5)-r.start)/864e5));return [['专注时长',human(seconds)],['日均专注',human(seconds/days)],['收获番茄',`${count} 个`],['放弃记录',`${rows.filter(r=>r.outcome==='abandoned').length} 次`]].map(([k,v])=>`<div><span>${k}</span><b>${v}</b></div>`).join('')}
function renderData(){const rows=currentRows();$$('.metric-row').forEach(el=>el.innerHTML=metrics(rows));const title=new Date(anchor).toLocaleDateString('zh-CN',{year:'numeric',month:'long',...(period==='D'?{day:'numeric'}:{})});$$('.page-trend .header-mid>span,.page-pomodoro .header-mid>span').forEach(el=>el.textContent=title);$$('.page-trend .period-tabs button,.page-pomodoro .period-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.period===period));
 const total=rows.filter(x=>x.outcome==='finished').reduce((s,r)=>s+r.seconds,0);
 const grouped=state.tags.map(t=>({t,rows:rows.filter(r=>r.tagId===t.id)})).filter(x=>x.rows.length);
 for(const [selector,cls] of [['#trendSide','trend-item'],['#pomodoroSide','pomo-item']]){$(selector).innerHTML=grouped.map(({t,rows})=>{const sec=rows.filter(r=>r.outcome==='finished').reduce((s,r)=>s+r.seconds,0);return `<button class="${cls}" data-detail="${esc(t.id)}"><span class="copy"><b>${esc(t.name)}</b><small>${human(sec)}</small></span><span class="tag-meter" style="--tag:${t.color};--share:${total?Math.round(sec/total*100):0}%"></span><em>${total?Math.round(sec/total*100):0}% ›</em></button>`}).join('')||'<div class="empty">这个时段还没有记录</div>';$(selector).querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>showRecords(rows.filter(r=>r.tagId===b.dataset.detail),tag(b.dataset.detail).name))}
 $('#tomatoWall').innerHTML=rows.filter(reward).map(r=>`<button data-session="${esc(r.id)}"><img src="assets/tomato-small.png" alt="${esc(tag(r.tagId).name)} ${human(r.seconds)}"></button>`).join('')||'<p class="empty">完成一次专注，收获你的第一个番茄。</p>';$$('[data-session]').forEach(b=>b.onclick=()=>editRecord(state.sessions.find(r=>r.id===b.dataset.session)));drawTrend();}
function showRecords(rows,title){show(title,`<div class="record-list">${rows.map(r=>`<button data-record="${esc(r.id)}"><b>${esc(new Date(r.start).toLocaleString('zh-CN'))}</b><span>${human(r.seconds)} · ${r.manual?'补录':r.outcome==='finished'?'完成':'放弃'} ›</span></button>`).join('')||'还没有记录'}</div>`);$$('[data-record]').forEach(b=>b.onclick=()=>editRecord(state.sessions.find(r=>r.id===b.dataset.record)))}
const inputTime=value=>{const d=new Date(value);return new Date(value-d.getTimezoneOffset()*60000).toISOString().slice(0,16)};
function editRecord(record){show(record?'专注记录':'补录专注',`<form id="recordForm"><label>标签<select id="recordTag">${state.tags.map(t=>`<option value="${esc(t.id)}" ${t.id===(record?.tagId||state.selectedTag)?'selected':''}>${esc(t.name)}</option>`).join('')}</select></label><label>开始时间<input type="datetime-local" id="recordStart" required value="${inputTime(record?.start||Date.now()-25*60e3)}"></label><label>时长（分钟）<input type="number" id="recordMinutes" min="1" max="1440" value="${Math.max(1,Math.floor((record?.seconds||1500)/60))}"></label><p>${record?'调整时长后保留原记录的完成状态。':'补录会计入统计，不奖励番茄。'}</p></form>`,[['saveRecord','保存','primary'],...(record?[['deleteRecord','删除记录','danger']]:[]),['closeDialog','取消']]);
 $('#saveRecord').onclick=()=>{const st=new Date($('#recordStart').value).getTime(),seconds=Number($('#recordMinutes').value)*60;if(!Number.isFinite(st)||!Number.isInteger(seconds)||seconds<60||seconds>86400||st+seconds*1000>Date.now())return toast('请填写已经结束的有效时间段');if(record)Object.assign(record,{tagId:$('#recordTag').value,start:st,end:st+seconds*1000,seconds});else state.sessions.push({id:makeId(),tagId:$('#recordTag').value,start:st,end:st+seconds*1000,seconds,outcome:'finished',manual:true});modal.close();changed()};
 $('#deleteRecord')?.addEventListener('click',()=>{show('删除这条记录？','<p>对应番茄也会从首页移除。</p>',[['confirmDelete','删除','danger'],['closeDialog','取消']]);$('#confirmDelete').onclick=()=>{state.sessions=state.sessions.filter(r=>r.id!==record.id);modal.close();changed()}});
}
for(const root of $$('.page-trend,.page-pomodoro')){root.querySelectorAll('.period-tabs button').forEach((b,i)=>{b.dataset.period=['D','W','M','Y'][i];b.textContent=['日','周','月','年'][i];b.onclick=()=>{period=b.dataset.period;renderData()}});root.querySelectorAll('.header-mid>button').forEach((b,i)=>b.onclick=()=>{const d=new Date(anchor),delta=i===0?-1:1;if(period==='D')d.setDate(d.getDate()+delta);else if(period==='W')d.setDate(d.getDate()+delta*7);else if(period==='M'){d.setDate(1);d.setMonth(d.getMonth()+delta)}else d.setFullYear(d.getFullYear()+delta);anchor=d.getTime();renderData()})}
$$('.plus-round').forEach(b=>b.onclick=()=>editRecord());
function drawTrend(){const c=$('#trendChart'),rect=c.getBoundingClientRect();if(rect.width<=0||rect.height<=0)return;const dpr=Math.min(devicePixelRatio||1,2);c.width=rect.width*dpr;c.height=rect.height*dpr;const ctx=c.getContext('2d');ctx.scale(dpr,dpr);const rows=currentRows().filter(r=>r.outcome==='finished'),r=range(period,anchor);const n=period==='Y'?12:period==='D'?24:period==='W'?7:new Date(new Date(r.end).getFullYear(),new Date(r.end).getMonth(),0).getDate();const bins=Array.from({length:n},()=>new Map());for(const item of rows){const d=new Date(item.start);const i=period==='Y'?d.getMonth():period==='D'?d.getHours():period==='W'?Math.round((dayStart(item.start)-r.start)/864e5):d.getDate()-1;if(!bins[i])continue;bins[i].set(item.tagId,(bins[i].get(item.tagId)||0)+item.seconds/60)}const max=Math.max(60,...bins.map(b=>[...b.values()].reduce((a,v)=>a+v,0))),W=rect.width-48,H=rect.height-36;ctx.font='11px -apple-system';for(let i=0;i<5;i++){const y=8+H*i/4;ctx.strokeStyle='#ece8e5';ctx.beginPath();ctx.moveTo(36,y);ctx.lineTo(rect.width,y);ctx.stroke();ctx.fillStyle='#a49c96';ctx.fillText(String(Math.round(max*(4-i)/4)),0,y+4)}bins.forEach((b,i)=>{let y=8+H;for(const [id,val] of b){const h=val/max*H;y-=h;ctx.fillStyle=tag(id).color;ctx.fillRect(40+i*W/n,y,Math.max(2,W/n*.62),h)}if(i%Math.ceil(n/8)===0){ctx.fillStyle='#a49c96';ctx.fillText(String(period==='D'?i:i+1),40+i*W/n,rect.height-5)}})}
function renderCalendar(){const r=range(calendarMode,calendarAnchor),days=calendarMode==='D'?1:7;$('#weekHead').style.gridTemplateColumns=`repeat(${days},1fr)`;$('#weekGrid').style.backgroundSize=`100% 60px,${100/days}% 100%`;$('#weekHead').innerHTML=Array.from({length:days},(_,i)=>{const d=new Date(r.start);d.setDate(d.getDate()+i);return `<div class="${dayStart(d.getTime())===dayStart(Date.now())?'today':''}"><span>${d.toLocaleDateString('zh-CN',{weekday:'short'})}</span><b>${d.getDate()}</b></div>`}).join('');$('#hours').innerHTML=Array.from({length:24},(_,i)=>`<span style="top:${i*60}px">${String(i).padStart(2,'0')}:00</span>`).join('');$('#weekGrid').innerHTML='';for(const row of state.sessions){for(let i=0;i<days;i++){const d=new Date(r.start);d.setDate(d.getDate()+i);const ds=d.getTime(),next=new Date(d);next.setDate(next.getDate()+1);if(row.start>=next.getTime()||row.end<=ds)continue;const a=new Date(Math.max(ds,row.start)),b=new Date(Math.min(next.getTime(),row.end));const top=a.getHours()*60+a.getMinutes(),end=row.end>=next.getTime()?1440:b.getHours()*60+b.getMinutes();const e=document.createElement('button');e.className='event';e.style.cssText=`left:calc(${i/days*100}% + 3px);width:calc(${100/days}% - 6px);top:${top}px;height:${Math.max(22,end-top)}px;background:${tag(row.tagId).color};opacity:${row.outcome==='abandoned'?.55:1}`;e.innerHTML=`<b>${esc(tag(row.tagId).name)}</b><small>${human(row.seconds)}</small>`;e.onclick=()=>editRecord(row);$('#weekGrid').append(e)}}$('.calendar-mid>span').textContent=new Date(r.start).toLocaleDateString('zh-CN',{month:'short',day:'numeric'});$('.page-calendar .page-header>strong').textContent=new Date(calendarAnchor).toLocaleDateString('zh-CN',{year:'numeric',month:'long'});}
$$('.calendar-mid>button').forEach((b,i)=>b.onclick=()=>{const d=new Date(calendarAnchor);d.setDate(d.getDate()+(i===0?-1:1)*(calendarMode==='D'?1:7));calendarAnchor=d.getTime();renderCalendar()});$$('.calendar-mid .period-tabs button').forEach((b,i)=>b.onclick=()=>{calendarMode=i===0?'D':'W';$$('.calendar-mid .period-tabs button').forEach(x=>x.classList.toggle('active',x===b));renderCalendar()});
function render(){renderTimer();if(page==='tags')renderTags();if(['trend','pomodoro'].includes(page))renderData();if(page==='calendar')renderCalendar()}
let audioContext=null,noiseSource=null,noiseGain=null;
function getAudio(){audioContext||=new (window.AudioContext||window.webkitAudioContext)();audioContext.resume().catch(()=>{});return audioContext}
function beep(){try{const a=getAudio(),o=a.createOscillator(),g=a.createGain();o.frequency.value=660;g.gain.setValueAtTime(.1,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.8);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+.8)}catch{}}
function noise(on){try{if(noiseSource){noiseSource.stop();noiseSource=null}if(on){const a=getAudio(),buffer=a.createBuffer(1,a.sampleRate*2,a.sampleRate),data=buffer.getChannelData(0);let prev=0;for(let i=0;i<data.length;i++){prev=(prev+(Math.random()*2-1)*.02)/1.02;data[i]=prev*3.5}noiseSource=a.createBufferSource();noiseSource.buffer=buffer;noiseSource.loop=true;noiseGain=a.createGain();noiseGain.gain.value=.25;noiseSource.connect(noiseGain).connect(a.destination);noiseSource.start()}}catch{toast('浏览器暂时无法播放声音')}}
$('#soundBtn').onclick=()=>{state.settings.noise=!state.settings.noise;noise(state.settings.noise);toast(state.settings.noise?'白噪声已开启':'白噪声已关闭');changed()};
document.addEventListener('pointerdown',()=>{try{getAudio();if(state.settings.noise)noise(true)}catch{}},{once:true});
$('#settingsBtn').onclick=()=>{
 $('#menuPopover').classList.add('hidden');const p=state.settings;
 show('设置',`<form id="settingsForm"><label>短休息（分钟）<input id="shortRest" type="number" min="1" max="60" value="${p.short}"></label><label>长休息（分钟）<input id="longRest" type="number" min="1" max="120" value="${p.long}"></label><label>长休息间隔（次）<input id="cycles" type="number" min="1" max="12" value="${p.cycles}"></label><label>首页番茄<select id="tomatoWindow">${[['week','本周'],['lastweek','上周'],['month','本月'],['quarter','近三个月']].map(([v,l])=>`<option value="${v}" ${p.window===v?'selected':''}>${l}</option>`).join('')}</select></label><label class="check">显示放弃记录<input id="showFailed" type="checkbox" ${p.showFailed?'checked':''}></label><label class="check">完成提示音<input id="finishSound" type="checkbox" ${p.sound?'checked':''}></label></form>`,[['saveSettings','保存','primary'],['notifyPermission','开启桌面提醒'],['motionPermission','开启体感重力'],['exportData','导出备份'],['importData','导入备份'],['closeDialog','关闭']]);
 $('#saveSettings').onclick=()=>{const short=Number($('#shortRest').value),long=Number($('#longRest').value),cycles=Number($('#cycles').value);if(![short,long,cycles].every(Number.isInteger)||short<1||short>60||long<1||long>120||cycles<1||cycles>12)return toast('休息时长或循环次数超出范围');Object.assign(p,{short,long,cycles,window:$('#tomatoWindow').value,showFailed:$('#showFailed').checked,sound:$('#finishSound').checked});modal.close();changed()};
 $('#notifyPermission').onclick=()=>send('focus-notification-permission');
 $('#motionPermission').onclick=async()=>{try{if(typeof DeviceOrientationEvent==='undefined')throw Error();if(typeof DeviceOrientationEvent.requestPermission==='function'&&await DeviceOrientationEvent.requestPermission()!=='granted')throw Error();state.settings.gravity=true;changed();toast('体感重力已开启')}catch{toast('当前浏览器没有开放体感权限，仍可拖动番茄')}};
 $('#exportData').onclick=()=>send('focus-export',{state});
 $('#importData').onclick=()=>{if(state.active)return toast('请先结束当前计时');const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=async()=>{try{const file=input.files[0];if(!file)return;if(file.size>2e6)throw Error('文件超过 2 MB');const incoming=validateState(JSON.parse(await file.text()));show('导入备份？',`<p>将替换当前标签和记录，共 ${incoming.sessions.length} 条。建议先导出当前备份。</p>`,[['confirmImport','替换并导入','danger'],['closeDialog','取消']]);$('#confirmImport').onclick=()=>{state=incoming;modal.close();changed();toast('备份已导入')}}catch(e){toast(e.message)}};input.click()};
};
const canvas=$('#tomatoPhysics'),ctx=canvas.getContext('2d'),tomatoImage=new Image();tomatoImage.src='assets/tomato.png';let bodies=[],width=1,height=1,last=performance.now(),gravity={x:0,y:.22},drag=null,down=null;
function hash(s){let n=0;for(let i=0;i<s.length;i++)n=(Math.imul(n,31)+s.charCodeAt(i))>>>0;return n}
function syncBodies(){const rows=visibleTomatoes().slice(-300),old=new Map(bodies.map(b=>[b.id,b]));bodies=rows.map((r,i)=>{const found=old.get(r.id);if(found){found.failed=r.outcome==='abandoned';return found}const side=Math.max(36,Math.min(90,Math.floor(r.seconds/60*.422857+33.8857)));return{id:r.id,x:side/2+hash(r.id)%Math.max(1,Math.floor(width-side)),y:-side-i*3,r:side/2,vx:0,vy:0,a:(hash(r.id)%60-30)/50,spin:0,failed:r.outcome==='abandoned'}})}
function resize(){const box=canvas.getBoundingClientRect();if(box.width>0&&box.height>0){const oldW=width,oldH=height;width=box.width;height=box.height;const dpr=Math.min(devicePixelRatio||1,2);canvas.width=width*dpr;canvas.height=height*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);for(const b of bodies){b.x=b.x/oldW*width;b.y=b.y/oldH*height}}drawTrend()}
function point(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
canvas.addEventListener('pointerdown',e=>{const p=point(e);const b=[...bodies].reverse().find(b=>Math.hypot(b.x-p.x,b.y-p.y)<b.r);if(!b)return;canvas.setPointerCapture(e.pointerId);down={x:p.x,y:p.y,t:performance.now()};drag={body:b,p,t:performance.now()};b.vx=0;b.vy=0});
canvas.addEventListener('pointermove',e=>{if(!drag)return;const p=point(e),now=performance.now(),dt=Math.max(8,now-drag.t);drag.body.vx=(p.x-drag.p.x)/dt*16.7;drag.body.vy=(p.y-drag.p.y)/dt*16.7;drag.body.x=p.x;drag.body.y=p.y;drag.p=p;drag.t=now});
function release(e){if(!drag)return;const b=drag.body,p=point(e);if(performance.now()-down.t<250&&Math.hypot(p.x-down.x,p.y-down.y)<8){b.vy=-7;b.vx=(Math.random()-.5)*4;b.spin=.04}else b.spin=b.vx*.003;drag=null;down=null}
canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',()=>{drag=null;down=null});
window.addEventListener('deviceorientation',e=>{if(!state.settings.gravity||e.gamma===null||e.beta===null)return;gravity.x=Math.max(-.45,Math.min(.45,e.gamma/90*.45));gravity.y=Math.max(.05,Math.min(.45,e.beta/90*.45))});
function animate(now){const dt=Math.min(2,(now-last)/16.7);last=now;if(page==='focus'&&!document.hidden){ctx.clearRect(0,0,width,height);for(const b of bodies){if(drag?.body===b)continue;b.vx+=gravity.x*dt;b.vy+=gravity.y*dt;b.x+=b.vx*dt;b.y+=b.vy*dt;b.a+=b.spin*dt;b.spin*=.995;if(b.x<b.r){b.x=b.r;b.vx=Math.abs(b.vx)*.5}if(b.x>width-b.r){b.x=width-b.r;b.vx=-Math.abs(b.vx)*.5}if(b.y>height-b.r){b.y=height-b.r;b.vy=-Math.abs(b.vy)*.25;b.vx*=.96}if(b.y< -200)b.y=-200}
 // Spatial buckets bound collision work when many sessions have accumulated.
 const grid=new Map(),cell=100;for(const b of bodies){const gx=Math.floor(b.x/cell),gy=Math.floor(b.y/cell);for(let dx=-1;dx<=1;dx++)for(let dy=-1;dy<=1;dy++){for(const a of grid.get(`${gx+dx},${gy+dy}`)||[]){const x=b.x-a.x,y=b.y-a.y,d=Math.hypot(x,y),min=a.r+b.r;if(d>0&&d<min){const nx=x/d,ny=y/d,o=(min-d)*.51;if(drag?.body!==a){a.x-=nx*o;a.y-=ny*o}if(drag?.body!==b){b.x+=nx*o;b.y+=ny*o}const v=(b.vx-a.vx)*nx+(b.vy-a.vy)*ny;if(v<0){const imp=-v*.4;a.vx-=imp*nx;a.vy-=imp*ny;b.vx+=imp*nx;b.vy+=imp*ny}}}}const key=`${gx},${gy}`;if(!grid.has(key))grid.set(key,[]);grid.get(key).push(b)}
 if(tomatoImage.complete&&tomatoImage.naturalWidth)for(const b of bodies){ctx.save();ctx.translate(b.x,b.y);ctx.rotate(b.a);ctx.globalAlpha=b.failed?.38:1;ctx.drawImage(tomatoImage,-b.r,-b.r,b.r*2,b.r*2);ctx.restore()}}
 requestAnimationFrame(animate)}
function tick(){if(!readOnly){const row=advance(state);if(row){changed();send('focus-awake',{active:false});if(!row.rest)finished(row);else{if(state.settings.sound)beep();toast('休息结束');send('focus-notify',{title:'休息结束',body:'准备开始下一轮专注。'})}}}renderTimer()}
window.addEventListener('resize',resize);window.addEventListener('message',e=>{if(e.source!==parent)return;if(e.data?.type==='focus-save-status'){if(e.data.status==='saved'){}else if(e.data.status==='conflict'){readOnly=true;show('另一台设备已有更新','<p>当前页面已停止修改，请先导出本页记录，再重新打开，避免覆盖另一台设备的记录。</p>',[['exportConflict','导出本页记录'],['reloadConflict','重新加载']]);$('#exportConflict').onclick=()=>send('focus-export',{state});$('#reloadConflict').onclick=()=>send('focus-reload')}else toast(e.data.message||'同步失败，正在保留本页修改')}if(e.data?.type==='focus-permission-result')toast(e.data.message)});
document.addEventListener('visibilitychange',()=>{if(!document.hidden){tick();resize()}});
document.addEventListener('keydown',e=>{if(e.code==='Space'&&!e.repeat&&page==='focus'&&!modal.open&&!['INPUT','TEXTAREA','SELECT','BUTTON'].includes(e.target.tagName)){e.preventDefault();if(!state.active)startFocus();else if(togglePause(state))changed()}});
resize();syncBodies();render();tick();requestAnimationFrame(animate);setInterval(tick,1000);send('focus-ready');send('focus-awake',{active:!!state.active});
