import test from 'node:test';import assert from 'node:assert/strict';
import {createHandler,OWNER_ID} from '../../supabase/functions/owner-focus/handler.mjs';import {defaults} from './engine.mjs';
const user=(id=OWNER_ID,role='owner')=>({id,app_metadata:{role}});
function make(actor){let calls=0;const admin={auth:{getUser:async()=>({data:{user:actor},error:null})},from:()=>{calls++;throw Error('unexpected database access')}};return {handler:createHandler({admin,appHTML:'private'}),calls:()=>calls}}
function req(body={action:'boot'},token='test-token',origin='https://evera.top'){return new Request('https://unit.test/owner-focus',{method:'POST',headers:{...(token?{Authorization:`Bearer ${token}`} : {}),Origin:origin,'Content-Type':'application/json'},body:JSON.stringify(body)})}
test('no auth cannot obtain code or touch database',async()=>{const x=make(user());const r=await x.handler(req({},''));assert.equal(r.status,404);assert.equal(x.calls(),0);assert.doesNotMatch(await r.text(),/private/)});
test('ordinary and user-metadata forged owner blocked',async()=>{for(const actor of [user(OWNER_ID,'user'),{id:OWNER_ID,user_metadata:{role:'owner'}},user('someone-else','owner')]){const x=make(actor),r=await x.handler(req());assert.equal(r.status,404);assert.equal(x.calls(),0)}});
test('untrusted origin blocked before querying user data',async()=>{const x=make(user());assert.equal((await x.handler(req({},'test','https://other.test'))).status,404);assert.equal(x.calls(),0)});
test('state-changing requests validate structure',async()=>{const x=make(user());const r=await x.handler(req({action:'save',revision:1,state:{}}));assert.equal(r.status,400);assert.equal(x.calls(),0)});
test('boot injects escaped state only after server owner verification',async()=>{const s=defaults();s.tags[0].name='</script><script>bad()</script>';const admin={auth:{getUser:async()=>({data:{user:user()}})},from:()=>({upsert:async()=>({error:null}),select:()=>({eq:()=>({single:async()=>({data:{state:s,revision:8},error:null})})})})};const r=await createHandler({admin,appHTML:'<script>__FOCUS_STATE__</script>'})(req());assert.equal(r.status,200);const data=await r.json();assert.equal(data.revision,8);assert.ok(!data.html.includes('<script>bad()'));assert.match(data.html,/\\u003c/);assert.match(r.headers.get('cache-control'),/no-store/)});
test('compare-and-swap refuses concurrent stale save',async()=>{let expected;const query={eq:(key,value)=>{if(key==='revision')expected=value;return query},select:()=>query,maybeSingle:async()=>({data:null,error:null})};const admin={auth:{getUser:async()=>({data:{user:user()}})},from:()=>({update:()=>query})};const r=await createHandler({admin,appHTML:''})(req({action:'save',revision:4,state:defaults()}));assert.equal(r.status,409);assert.equal(expected,4)});
