import { createClient } from 'npm:@supabase/supabase-js@2.111.0'
const SUPABASE_URL=Deno.env.get('SUPABASE_URL')||''
const SERVICE_KEY=(()=>{try{const x=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')||'{}');if(x?.default)return String(x.default)}catch{}return Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||''})()
const GH_TOKEN=Deno.env.get('EVERFLOW_GITHUB_TOKEN')||''
const REPO='EverflowCN/everflow-paper',WORKFLOW='update-oxygen.yml'
const allowed=new Set(['https://evera.top','https://www.evera.top'])
const corsFor=(req:Request)=>{const o=req.headers.get('Origin')||'';return {'Access-Control-Allow-Origin':allowed.has(o)?o:'https://evera.top','Vary':'Origin','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'}}
async function gh(path:string,init:RequestInit={}){const h:any={'Accept':'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28',...(init.headers||{})};if(GH_TOKEN)h.Authorization=`Bearer ${GH_TOKEN}`;const r=await fetch(`https://api.github.com/repos/${REPO}${path}`,{...init,headers:h});const text=await r.text();let data:any=null;try{data=text?JSON.parse(text):null}catch{data=text}if(!r.ok)throw Object.assign(new Error(data?.message||`GitHub ${r.status}`),{status:r.status,data});return data}
async function counts(){try{const r=await fetch(`https://raw.githubusercontent.com/${REPO}/main/site/data/oxygen.json`,{cache:'no-store'});if(!r.ok)throw new Error(`oxygen_json_${r.status}`);const j=await r.json();const out:any={};for(const k of ['ds','co','os','cn'])out[k]=Array.isArray(j?.subjects?.[k]?.items)?j.subjects[k].items.length:Array.isArray(j?.subjects?.[k]?.courses)?j.subjects[k].courses.length:Array.isArray(j?.[k])?j[k].length:0;return {counts:out,updatedAt:j?.updatedAt||j?.updated_at||null,sourceStatus:j?.source?.syncStatus||j?.syncStatus||j?.status||null,message:j?.source?.message||''}}catch(e){console.error(e);return {counts:{ds:0,co:0,os:0,cn:0},updatedAt:null,sourceStatus:'unavailable',message:'oxygen.json 暂时无法读取'}}}
Deno.serve(async req=>{const cors=corsFor(req),json=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,'Content-Type':'application/json; charset=utf-8'}});if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'not_found'},404);if(!SUPABASE_URL||!SERVICE_KEY)return json({error:'service_unavailable'},503);const token=(req.headers.get('Authorization')||'').replace(/^Bearer\s+/,'');const admin=createClient(SUPABASE_URL,SERVICE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});const {data:{user},error}=await admin.auth.getUser(token);if(error||!user||user.app_metadata?.role!=='owner')return json({error:'not_found'},404);let body:any={};try{body=await req.json()}catch{}const action=String(body.action||'status');try{
if(action==='status'){const [runs,course]=await Promise.all([gh(`/actions/workflows/${WORKFLOW}/runs?per_page=10`).catch(e=>({workflow_runs:[],error:e?.message||'github_status_failed'})),counts()]);const {data:history,error:historyError}=await admin.from('oxygen_update_runs').select('*').order('started_at',{ascending:false}).limit(20);if(historyError)throw historyError;return json({ok:true,tokenConfigured:Boolean(GH_TOKEN),workflowRuns:runs?.workflow_runs||[],githubStatusError:runs?.error||null,course,history:history||[]})}
if(action==='dispatch'){if(!GH_TOKEN){await admin.from('oxygen_update_runs').insert({trigger_type:'manual',status:'blocked',summary:{reason:'github_token_missing'},finished_at:new Date().toISOString(),triggered_by:user.id});return json({error:'github_token_missing'},503)}await gh(`/actions/workflows/${WORKFLOW}/dispatches`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ref:'main'})});const {data:row,error:rowError}=await admin.from('oxygen_update_runs').insert({trigger_type:'manual',status:'queued',summary:{workflow:WORKFLOW},triggered_by:user.id}).select().single();if(rowError)throw rowError;await admin.from('admin_audit').insert({actor_user_id:user.id,action:'oxygen_sync_dispatch',detail:{workflow:WORKFLOW}});return json({ok:true,run:row})}
if(action==='retry'){if(!GH_TOKEN)return json({error:'github_token_missing'},503);let runId=Number(body.runId)||0;if(!runId){const rr=await gh(`/actions/workflows/${WORKFLOW}/runs?status=failure&per_page=1`);runId=Number(rr?.workflow_runs?.[0]?.id)||0}if(!runId)return json({error:'no_failed_run'},404);await gh(`/actions/runs/${runId}/rerun-failed-jobs`,{method:'POST'});const {data:row,error:rowError}=await admin.from('oxygen_update_runs').insert({trigger_type:'retry',status:'queued',github_run_id:runId,summary:{workflow:WORKFLOW},triggered_by:user.id}).select().single();if(rowError)throw rowError;await admin.from('admin_audit').insert({actor_user_id:user.id,action:'oxygen_sync_retry',detail:{github_run_id:runId}});return json({ok:true,run:row})}
return json({error:'not_found'},404)}catch(e:any){console.error(e);return json({error:'operation_failed',message:e?.message||'failed'},500)}})