import { createClient } from 'npm:@supabase/supabase-js@2.111.0'

const SUPABASE_URL = Deno.env.get('SUPABASE_URL') || ''
const SERVICE_KEY = (()=>{try{const x=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')||'{}');if(x?.default)return String(x.default)}catch{}return Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||''})()
const REPO='EverflowCN/everflow-paper'
const MID=378777885
const AUTHOR='就是氧气11'
const COLLECTION_NAME='27考研408计算机基础综合合集'
const COLLECTION_LIST_API='https://api.bilibili.com/x/polymer/web-space/home/seasons_series'
const COLLECTION_ARCHIVES_API='https://api.bilibili.com/x/polymer/web-space/seasons_archives_list'
const SEARCH_API='https://api.bilibili.com/x/web-interface/search/type'
const allowed=new Set(['https://evera.top','https://www.evera.top'])
const subjects=['ds','co','os','cn'] as const
const corsFor=(req:Request)=>{const o=req.headers.get('Origin')||'';return {'Access-Control-Allow-Origin':allowed.has(o)?o:'https://evera.top','Vary':'Origin','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'}}
const clean=(s:any)=>String(s||'').replace(/<[^>]+>/g,'').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\s+/g,' ').trim()
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms))
const headers={'User-Agent':'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36','Referer':`https://space.bilibili.com/${MID}/lists`,'Accept':'application/json,text/plain,*/*','Accept-Language':'zh-CN,zh;q=0.9,en;q=0.7'}
async function requestJson(url:string,params:Record<string,string|number>,referer?:string){const u=new URL(url);for(const [k,v] of Object.entries(params))u.searchParams.set(k,String(v));let last:any=null;for(let i=0;i<3;i++){try{const r=await fetch(u,{headers:{...headers,...(referer?{Referer:referer}:{})},signal:AbortSignal.timeout(22000)});if(!r.ok)throw new Error(`HTTP_${r.status}`);const j=await r.json();if(j?.code!==0)throw new Error(`BILI_${j?.code}_${j?.message||''}`);return j}catch(e){last=e;if(i<2)await sleep(1400+i*1800)}}throw last||new Error('request_failed')}
function belongs(subject:string,titleRaw:any){const t=clean(titleRaw);if(subject==='ds')return t.startsWith('27数据结构强化')||t==='27考研408强化更新内容与方法论-氧气版';if(subject==='co')return t.startsWith('27组成原理强化')||t.startsWith('27计算机组成原理强化')||t.includes('计算机组成原理强化课更新指南');if(subject==='os')return t.startsWith('27操作系统强化')||t.includes('操作系统强化课更新指南');if(subject==='cn')return t.startsWith('27计网强化')||t.startsWith('27计算机网络强化')||t.includes('计算机网络强化课更新指南');return false}
const prefixes:any={ds:['27数据结构强化-','27数据结构强化—','27数据结构强化：'],co:['27组成原理强化-','27组成原理强化—','27组成原理强化：','27计算机组成原理强化-','27计算机组成原理强化—','27计算机组成原理强化：'],os:['27操作系统强化-','27操作系统强化—','27操作系统强化：'],cn:['27计网强化-','27计网强化—','27计网强化：','27计算机网络强化-','27计算机网络强化—','27计算机网络强化：']}
const keywords:any={ds:['27数据结构强化'],co:['27组成原理强化','27计算机组成原理强化'],os:['27操作系统强化'],cn:['27计网强化','27计算机网络强化']}
function normalizeTitle(subject:string,raw:any){let t=clean(raw);if(t.includes('强化课更新指南')||t.includes('强化更新内容与方法论'))return t;for(const p of prefixes[subject]||[])if(t.startsWith(p)){t=t.slice(p.length).trim();break}return t.replace(/^[\s\-—：:]+|[\s\-—：:]+$/g,'')}
function duration(raw:any){if(typeof raw==='number'){let s=Math.max(0,Math.floor(raw)),h=Math.floor(s/3600);s%=3600;const m=Math.floor(s/60),sec=s%60;return h?`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`:`${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`}const x=String(raw||'').trim();if(!x)return'';const a=x.split(':').map(Number);if(a.some(Number.isNaN))return x;if(a.length===2&&a[0]>=60){const h=Math.floor(a[0]/60),m=a[0]%60;return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(a[1]).padStart(2,'0')}`}return a.map(n=>String(n).padStart(2,'0')).join(':')}
function itemFrom(subject:string,row:any){const title=normalizeTitle(subject,row?.title);const bvid=String(row?.bvid||'').trim();const pub=Number(row?.pubdate||row?.ctime||0)||0;return {subject,item_id:`${subject}|${title}`,title,duration:duration(row?.duration),url:bvid?`https://www.bilibili.com/video/${bvid}/`:String(row?.arcurl||'').replace(/^http:/,'https:'),bvid,published_at:pub,source_updated_at:new Date().toISOString()}}
async function collectionArchives(){const first=await requestJson(COLLECTION_LIST_API,{mid:MID,page_num:1,page_size:50,web_location:'333.999'});const seasons=first?.data?.items_lists?.seasons_list||[];let seasonId=0,name='';for(const x of seasons){const m=x?.meta&&typeof x.meta==='object'?x.meta:x;const n=clean(m?.name);if(n===COLLECTION_NAME||n.includes(COLLECTION_NAME)){seasonId=Number(m?.season_id)||0;name=n;break}}if(!seasonId)throw new Error('collection_not_found');const referer=`https://space.bilibili.com/${MID}/lists/${seasonId}?type=season`;const one=await requestJson(COLLECTION_ARCHIVES_API,{mid:MID,season_id:seasonId,sort_reverse:'true',page_num:1,page_size:30},referer);let archives=[...(one?.data?.archives||[])];const total=Number(one?.data?.page?.total||archives.length)||archives.length;const size=Math.max(1,Number(one?.data?.page?.page_size||30));const pages=Math.max(1,Math.ceil(total/size));for(let p=2;p<=pages;p++){await sleep(350);const j=await requestJson(COLLECTION_ARCHIVES_API,{mid:MID,season_id:seasonId,sort_reverse:'true',page_num:p,page_size:size},referer);archives.push(...(j?.data?.archives||[]))}return {archives,seasonId,name}}
async function searchSubject(subject:string){const found=new Map<string,any>();for(const kw of keywords[subject]||[]){for(let page=1;page<=3;page++){const j=await requestJson(SEARCH_API,{search_type:'video',keyword:kw,order:'pubdate',page,page_size:20},'https://search.bilibili.com/');const rows=j?.data?.result||[];for(const row of rows){if(clean(row?.author)!==AUTHOR)continue;const it=itemFrom(subject,row);if(it.title)found.set(it.item_id,it)}if(rows.length<20)break;await sleep(300)}if(found.size)break}return [...found.values()].sort((a,b)=>(a.published_at-b.published_at)||a.title.localeCompare(b.title,'zh-CN'))}
async function discoverAll(){let archives:any[]=[],collectionMeta:any=null,collectionError='';try{const c=await collectionArchives();archives=c.archives;collectionMeta={method:'collection',seasonId:c.seasonId,collection:c.name,scanned:c.archives.length}}catch(e:any){collectionError=e?.message||String(e)}const out:any={},status:any={};for(const s of subjects){try{let rows=archives.filter(r=>belongs(s,r?.title)).map(r=>itemFrom(s,r)).filter(x=>x.title);let meta=collectionMeta;if(!rows.length){rows=await searchSubject(s);meta={method:'search',collectionError}}if(!rows.length)throw new Error('no_items');out[s]=rows;status[s]={ok:true,count:rows.length,method:meta?.method||'search'}}catch(e:any){out[s]=[];status[s]={ok:false,count:0,error:e?.message||String(e)}}}return {out,status,collectionError}}
async function tableCounts(admin:any){const {data,error}=await admin.from('oxygen_catalog').select('subject,item_id');if(error)throw error;const c:any={ds:0,co:0,os:0,cn:0};for(const r of data||[])if(c[r.subject]!==undefined)c[r.subject]++;return c}
async function staticCounts(){try{const r=await fetch(`https://raw.githubusercontent.com/${REPO}/main/site/data/oxygen.json`,{cache:'no-store'});if(!r.ok)throw new Error('static_unavailable');const j=await r.json();const c:any={};for(const s of subjects)c[s]=Array.isArray(j?.subjects?.[s]?.items)?j.subjects[s].items.length:0;return {counts:c,updatedAt:j?.updatedAt||null,sourceStatus:j?.source?.syncStatus||'seed',message:j?.source?.message||'',data:j}}catch{return {counts:{ds:0,co:0,os:0,cn:0},updatedAt:null,sourceStatus:'unavailable',message:'oxygen.json 暂时无法读取',data:null}}}
async function syncNative(admin:any,userId:string,triggerType:string){const started=new Date().toISOString();const {data:run,error:runError}=await admin.from('oxygen_update_runs').insert({trigger_type:triggerType,status:'running',summary:{mode:'supabase-native'},triggered_by:userId,started_at:started}).select().single();if(runError)throw runError;try{const d=await discoverAll();let ok=0;for(const s of subjects){if(!d.status[s]?.ok)continue;ok++;const rows=d.out[s];if(rows.length){const {error}=await admin.from('oxygen_catalog').upsert(rows,{onConflict:'subject,item_id'});if(error)throw error}}const counts=await tableCounts(admin);const syncStatus=ok===4?'ok':ok>0?'partial':'error';const message=ok===4?'Supabase 原生同步完成':ok>0?`部分同步成功 ${ok}/4`:'本轮同步失败';const now=new Date().toISOString();await admin.from('oxygen_catalog_meta').upsert({id:'default',updated_at:now,sync_status:syncStatus,message,subject_status:d.status,source:{mode:'supabase-native',collectionError:d.collectionError||''}},{onConflict:'id'});await admin.from('oxygen_update_runs').update({status:syncStatus==='ok'?'success':syncStatus,summary:{mode:'supabase-native',counts,subjectStatus:d.status},finished_at:now,log_excerpt:message}).eq('id',run.id);await admin.from('admin_audit').insert({actor_user_id:userId,action:triggerType==='retry'?'oxygen_sync_retry':'oxygen_sync_dispatch',detail:{mode:'supabase-native',counts,status:syncStatus}});return {ok:syncStatus!=='error',syncStatus,counts,subjectStatus:d.status,updatedAt:now,message,runId:run.id}}catch(e:any){const now=new Date().toISOString();await admin.from('oxygen_update_runs').update({status:'failure',summary:{mode:'supabase-native',error:e?.message||String(e)},finished_at:now,log_excerpt:String(e?.message||e).slice(0,1000)}).eq('id',run.id);throw e}}
async function publicWorkflowRuns(){try{const r=await fetch(`https://api.github.com/repos/${REPO}/actions/workflows/update-oxygen.yml/runs?per_page=8`,{headers:{Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28','User-Agent':'Everflow-Oxygen-Sync'}});if(!r.ok)return[];const j=await r.json();return j?.workflow_runs||[]}catch{return[]}}

Deno.serve(async req=>{const cors=corsFor(req),json=(b:any,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,'Content-Type':'application/json; charset=utf-8'}});if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'not_found'},404);if(!SUPABASE_URL||!SERVICE_KEY)return json({error:'service_unavailable'},503);const token=(req.headers.get('Authorization')||'').replace(/^Bearer\s+/,'');const admin=createClient(SUPABASE_URL,SERVICE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});const {data:{user},error}=await admin.auth.getUser(token);if(error||!user||user.app_metadata?.role!=='owner')return json({error:'not_found'},404);let body:any={};try{body=await req.json()}catch{}const action=String(body.action||'status');try{if(action==='status'){const [{data:meta},countsDb,staticData,{data:history},workflowRuns]=await Promise.all([admin.from('oxygen_catalog_meta').select('*').eq('id','default').maybeSingle(),tableCounts(admin),staticCounts(),admin.from('oxygen_update_runs').select('*').order('started_at',{ascending:false}).limit(20),publicWorkflowRuns()]);const dbTotal=Object.values(countsDb).reduce((a:any,b:any)=>a+Number(b||0),0);const useDb=Number(dbTotal)>0;const counts=useDb?countsDb:staticData.counts;return json({ok:true,manualSyncEnabled:true,syncMode:'supabase-native',tokenConfigured:false,workflowRuns,course:{counts,updatedAt:useDb?meta?.updated_at:staticData.updatedAt,sourceStatus:useDb?meta?.sync_status:staticData.sourceStatus,message:useDb?meta?.message:staticData.message},history:history||[]})}if(action==='dispatch')return json(await syncNative(admin,user.id,'manual'));if(action==='retry')return json(await syncNative(admin,user.id,'retry'));return json({error:'not_found'},404)}catch(e:any){console.error(e);return json({error:'operation_failed',message:e?.message||'failed'},500)}})
