create table if not exists public.study_checkin_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null check (event_type in ('course','practice','manual')),
  source_id text not null default '',
  item_id text not null default '',
  subject text not null default '',
  occurred_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists study_checkin_events_user_occurred_idx
  on public.study_checkin_events(user_id, occurred_at desc);
create index if not exists study_checkin_events_user_type_idx
  on public.study_checkin_events(user_id, event_type, occurred_at desc);

alter table public.study_checkin_events enable row level security;

drop policy if exists study_checkin_events_select_own on public.study_checkin_events;
create policy study_checkin_events_select_own on public.study_checkin_events
  for select using (auth.uid() = user_id);

drop policy if exists study_checkin_events_insert_own on public.study_checkin_events;
create policy study_checkin_events_insert_own on public.study_checkin_events
  for insert with check (auth.uid() = user_id);

drop policy if exists study_checkin_events_delete_own on public.study_checkin_events;
create policy study_checkin_events_delete_own on public.study_checkin_events
  for delete using (auth.uid() = user_id);

create or replace function public.log_course_checkin_event()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.done and (tg_op = 'INSERT' or not coalesce(old.done,false)) then
    insert into public.study_checkin_events(user_id,event_type,source_id,item_id,subject,occurred_at,metadata)
    values (
      new.user_id,
      'course',
      'course_states',
      new.course_id,
      new.subject,
      coalesce(new.completed_at,new.updated_at,now()),
      jsonb_build_object('device_id',coalesce(new.device_id,''))
    );
  end if;
  return new;
end;
$$;

drop trigger if exists trg_course_checkin_event on public.course_states;
create trigger trg_course_checkin_event
after insert or update of done on public.course_states
for each row execute function public.log_course_checkin_event();

create or replace function public.log_practice_checkin_event()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.status in ('done','mastered') and (
    tg_op = 'INSERT' or old.status not in ('done','mastered')
  ) then
    insert into public.study_checkin_events(user_id,event_type,source_id,item_id,subject,occurred_at,metadata)
    values (
      new.user_id,
      'practice',
      new.practice_id,
      new.item_id,
      new.subject,
      coalesce(new.first_done_at,new.last_attempt_at,new.updated_at,now()),
      jsonb_build_object('status',new.status)
    );
  end if;
  return new;
end;
$$;

drop trigger if exists trg_practice_checkin_event on public.practice_states;
create trigger trg_practice_checkin_event
after insert or update of status on public.practice_states
for each row execute function public.log_practice_checkin_event();

insert into public.study_checkin_events(user_id,event_type,source_id,item_id,subject,occurred_at,metadata)
select c.user_id,'course','course_states',c.course_id,c.subject,coalesce(c.completed_at,c.updated_at,now()),jsonb_build_object('backfill',true,'device_id',coalesce(c.device_id,''))
from public.course_states c
where c.done = true
  and not exists (
    select 1 from public.study_checkin_events e
    where e.user_id=c.user_id and e.event_type='course' and e.source_id='course_states' and e.item_id=c.course_id
  );

insert into public.study_checkin_events(user_id,event_type,source_id,item_id,subject,occurred_at,metadata)
select p.user_id,'practice',p.practice_id,p.item_id,p.subject,coalesce(p.first_done_at,p.last_attempt_at,p.updated_at,now()),jsonb_build_object('backfill',true,'status',p.status)
from public.practice_states p
where p.status in ('done','mastered')
  and not exists (
    select 1 from public.study_checkin_events e
    where e.user_id=p.user_id and e.event_type='practice' and e.source_id=p.practice_id and e.item_id=p.item_id
  );
