-- Everflow Workspace v3
-- Applied to production Supabase on 2026-08-11.

alter table public.membership_codes add column if not exists code_ciphertext text;
alter table public.membership_codes add column if not exists code_iv text;
alter table public.membership_codes add column if not exists cipher_version integer not null default 1;

alter table public.resource_hub_settings add column if not exists announcement text not null default '';
alter table public.resource_hub_settings add column if not exists announcement_enabled boolean not null default false;
alter table public.resource_hub_settings add column if not exists background_variant text not null default 'paper';
alter table public.resource_hub_items add column if not exists badge text not null default '';
alter table public.resource_hub_items add column if not exists accent text not null default 'default';

create table if not exists public.user_temp_credentials (
  user_id uuid primary key references auth.users(id) on delete cascade,
  password_ciphertext text not null,
  password_iv text not null,
  cipher_version integer not null default 1,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  version integer not null default 1,
  active boolean not null default true
);
alter table public.user_temp_credentials enable row level security;
drop policy if exists "owner can manage temp credentials" on public.user_temp_credentials;
create policy "owner can manage temp credentials" on public.user_temp_credentials
  for all using (public.is_everflow_owner()) with check (public.is_everflow_owner());
create index if not exists user_temp_credentials_created_at_idx on public.user_temp_credentials(created_at desc);
create index if not exists user_temp_credentials_created_by_idx on public.user_temp_credentials(created_by);

create table if not exists public.oxygen_update_runs (
  id bigint generated by default as identity primary key,
  trigger_type text not null default 'manual' check (trigger_type in ('manual','retry','automatic')),
  status text not null default 'queued' check (status in ('queued','running','success','failed','blocked')),
  github_run_id bigint,
  summary jsonb not null default '{}'::jsonb,
  log_excerpt text not null default '',
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  triggered_by uuid references auth.users(id) on delete set null
);
alter table public.oxygen_update_runs enable row level security;
drop policy if exists "owner can manage oxygen update runs" on public.oxygen_update_runs;
create policy "owner can manage oxygen update runs" on public.oxygen_update_runs
  for all using (public.is_everflow_owner()) with check (public.is_everflow_owner());
create index if not exists oxygen_update_runs_started_at_idx on public.oxygen_update_runs(started_at desc);
create index if not exists oxygen_update_runs_triggered_by_idx on public.oxygen_update_runs(triggered_by);