-- Everflow Membership v1
-- Applied to the production Supabase project on 2026-08-11.
-- Pro free-claim is enabled, but pro_free_until is intentionally NULL until the
-- official 2027 postgraduate entrance exam date is published. Update the config
-- and promo memberships together once that date is official.

create table if not exists public.membership_config (
  id text primary key default 'default' check (id = 'default'),
  pro_free_claim_enabled boolean not null default true,
  pro_free_until timestamptz,
  promo_title text not null default 'Pro 考研前限时免费',
  promo_copy text not null default '当前可直接免费开通 Pro；正式截止时间以后续公布的考研初试时间为准。',
  updated_at timestamptz not null default now()
);
insert into public.membership_config(id) values ('default') on conflict (id) do nothing;

create table if not exists public.memberships (
  user_id uuid primary key references auth.users(id) on delete cascade,
  plan text not null check (plan in ('member','pro')),
  status text not null default 'active' check (status in ('active','expired','revoked')),
  source text not null default 'manual',
  starts_at timestamptz not null default now(),
  expires_at timestamptz,
  updated_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.membership_codes (
  id uuid primary key default gen_random_uuid(),
  code_hash text not null unique,
  code_hint text not null,
  plan text not null check (plan in ('member','pro')),
  max_uses integer not null default 1 check (max_uses > 0 and max_uses <= 100000),
  used_count integer not null default 0 check (used_count >= 0),
  active boolean not null default true,
  redeem_expires_at timestamptz,
  grant_expires_at timestamptz,
  note text not null default '',
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.membership_code_redemptions (
  id bigint generated by default as identity primary key,
  code_id uuid not null references public.membership_codes(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  redeemed_at timestamptz not null default now(),
  unique(code_id,user_id)
);

create index if not exists idx_memberships_plan_status on public.memberships(plan,status);
create index if not exists idx_membership_codes_active on public.membership_codes(active,redeem_expires_at);
create index if not exists idx_membership_codes_created_by on public.membership_codes(created_by);
create index if not exists idx_membership_redemptions_user on public.membership_code_redemptions(user_id,redeemed_at desc);

alter table public.membership_config enable row level security;
alter table public.memberships enable row level security;
alter table public.membership_codes enable row level security;
alter table public.membership_code_redemptions enable row level security;

drop policy if exists "membership_config_public_read" on public.membership_config;
create policy "membership_config_public_read" on public.membership_config for select to anon, authenticated using (true);

drop policy if exists "memberships_select_own_or_owner" on public.memberships;
create policy "memberships_select_own_or_owner" on public.memberships for select to authenticated
using ((select auth.uid()) = user_id or (select public.is_everflow_owner()));

drop policy if exists "membership_codes_owner_read" on public.membership_codes;
create policy "membership_codes_owner_read" on public.membership_codes for select to authenticated
using ((select public.is_everflow_owner()));

drop policy if exists "membership_redemptions_own_or_owner" on public.membership_code_redemptions;
create policy "membership_redemptions_own_or_owner" on public.membership_code_redemptions for select to authenticated
using ((select auth.uid()) = user_id or (select public.is_everflow_owner()));

create or replace function public.claim_exam_pro(p_user_id uuid)
returns public.memberships
language plpgsql
security definer
set search_path = public
as $$
declare
  cfg public.membership_config;
  out_row public.memberships;
begin
  select * into cfg from public.membership_config where id='default';
  if cfg.pro_free_claim_enabled is not true then raise exception 'promo_closed'; end if;
  if cfg.pro_free_until is not null and cfg.pro_free_until <= now() then raise exception 'promo_closed'; end if;

  insert into public.memberships(user_id,plan,status,source,starts_at,expires_at,updated_at,metadata)
  values(p_user_id,'pro','active','promo_exam_2027',now(),cfg.pro_free_until,now(),jsonb_build_object('promo','exam_2027'))
  on conflict(user_id) do update set
    plan='pro', status='active', source='promo_exam_2027',
    expires_at=excluded.expires_at, updated_at=now(),
    metadata=coalesce(public.memberships.metadata,'{}'::jsonb) || excluded.metadata
  returning * into out_row;
  return out_row;
end;
$$;

create or replace function public.redeem_membership_code(p_user_id uuid, p_code_hash text)
returns public.memberships
language plpgsql
security definer
set search_path = public
as $$
declare
  c public.membership_codes;
  out_row public.memberships;
  already boolean;
begin
  select * into c from public.membership_codes where code_hash=p_code_hash for update;
  if c.id is null or c.active is not true then raise exception 'invalid_code'; end if;
  if c.redeem_expires_at is not null and c.redeem_expires_at <= now() then raise exception 'code_expired'; end if;
  select exists(select 1 from public.membership_code_redemptions where code_id=c.id and user_id=p_user_id) into already;
  if not already and c.used_count >= c.max_uses then raise exception 'code_exhausted'; end if;

  if not already then
    insert into public.membership_code_redemptions(code_id,user_id) values(c.id,p_user_id);
    update public.membership_codes set used_count=used_count+1 where id=c.id;
  end if;

  insert into public.memberships(user_id,plan,status,source,starts_at,expires_at,updated_at,metadata)
  values(p_user_id,c.plan,'active','redeem_code',now(),c.grant_expires_at,now(),jsonb_build_object('code_id',c.id))
  on conflict(user_id) do update set
    plan=case when public.memberships.plan='pro' or excluded.plan='pro' then 'pro' else 'member' end,
    status='active',
    source=case when public.memberships.plan='pro' and excluded.plan='member' then public.memberships.source else excluded.source end,
    expires_at=case
      when public.memberships.plan='pro' and excluded.plan='member' then public.memberships.expires_at
      when public.memberships.expires_at is null or excluded.expires_at is null then null
      else greatest(public.memberships.expires_at,excluded.expires_at)
    end,
    updated_at=now(),
    metadata=coalesce(public.memberships.metadata,'{}'::jsonb) || excluded.metadata
  returning * into out_row;
  return out_row;
end;
$$;

revoke all on function public.claim_exam_pro(uuid) from public, anon, authenticated;
revoke all on function public.redeem_membership_code(uuid,text) from public, anon, authenticated;
grant execute on function public.claim_exam_pro(uuid) to service_role;
grant execute on function public.redeem_membership_code(uuid,text) to service_role;
